# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-GB"
timezone: Europe/London
title: SDR Satcom
description: "Software-Defined Radio Satellite Communications."
email: sdrsatcom@myriadrf.org

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sdrsat.com" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/assets/images/site-logo.png"
masthead_title: " "

comments:
  provider: "discourse"
  discourse:
    server: discourse.myriadrf.org

twitter:
  username: "myriadrf"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-5468815-10"
    anonymize_ip: false # default

#include: [_pages]

# Site Footer
footer:
  links:
    - label: "Forum"
      icon: "fab fa-fw fa-discourse"
      url: "https://discourse.myriadrf.org/c/projects/sdr-satcom"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/myriadrf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/myriadrf"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/myriadrf/"


# Build settings

markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
